INSERT INTO products (name, description, price) VALUES ('iPhone 12', 'The latest smartphone from Apple', 999.99);
INSERT INTO products (name, description, price) VALUES ('Samsung Galaxy S21', 'Powerful Android smartphone with great camera', 899.99);
INSERT INTO products (name, description, price) VALUES ('Sony PlayStation 5', 'Next-generation gaming console with stunning graphics', 499.99);
INSERT INTO products (name, description, price) VALUES ('MacBook Pro', 'High-performance laptop for professionals', 1999.99);
INSERT INTO products (name, description, price) VALUES ('Dell XPS 15', 'Sleek and powerful Windows laptop', 1599.99);
INSERT INTO products (name, description, price) VALUES ('Amazon Echo Dot', 'Smart speaker with Alexa voice assistant', 49.99);
INSERT INTO products (name, description, price) VALUES ('Fitbit Charge 4', 'Advanced fitness tracker with built-in GPS', 149.99);
INSERT INTO products (name, description, price) VALUES ('Nintendo Switch', 'Versatile gaming console for at-home and on-the-go play', 299.99);
INSERT INTO products (name, description, price) VALUES ('GoPro HERO9 Black', 'High-quality action camera for capturing adventures', 449.99);
INSERT INTO products (name, description, price) VALUES ('Bose QuietComfort 35 II', 'Wireless noise-canceling headphones', 299.99);
INSERT INTO products (name, description, price) VALUES ('Canon EOS R5', 'Professional mirrorless camera with 8K video recording', 3899.99);
INSERT INTO products (name, description, price) VALUES ('Apple Watch Series 6', 'Advanced smartwatch with health and fitness features', 399.99);
INSERT INTO products (name, description, price) VALUES ('Google Pixel 5', 'Android smartphone with exceptional camera capabilities', 699.99);
INSERT INTO products (name, description, price) VALUES ('Microsoft Surface Pro 7', 'Versatile 2-in-1 laptop and tablet', 899.99);
INSERT INTO products (name, description, price) VALUES ('LG OLED CX Series', 'High-end OLED TV with stunning picture quality', 1999.99);
INSERT INTO products (name, description, price) VALUES ('Sony WH-1000XM4', 'Premium noise-canceling headphones with excellent sound', 349.99);
INSERT INTO products (name, description, price) VALUES ('Nikon D850', 'Professional DSLR camera with high-resolution sensor', 2999.99);
INSERT INTO products (name, description, price) VALUES ('iPad Air', 'Powerful tablet for productivity and entertainment', 599.99);
INSERT INTO products (name, description, price) VALUES ('Xbox Series X', 'Next-generation gaming console with fast loading times', 499.99);
INSERT INTO products (name, description, price) VALUES ('Samsung QLED Q90T', 'QLED TV with vibrant colors and impressive contrast', 2499.99);
